stages:
  - build
variables:
  CONTAINER_RELEASE_IMAGE: $IMAGE_DOCKER:$CI_COMMIT_TAG


build:
  image: docker:18
  services:
      - docker:18-dind
  stage: build
  script:
    - docker login -u "${USER_DOCKER}" -p "${PASSWORD_DOCKER}"
    - docker build --pull -t "$CONTAINER_RELEASE_IMAGE" -f docker/Dockerfile .
    - docker push "$CONTAINER_RELEASE_IMAGE"
  tags:
    - "tokend"

