const REVIEWABLE_REQUESTS_CREATOR = "REVIEWABLE_REQUESTS_CREATOR";
const TOKEN_FACTORY_EXECUTOR = "TOKEN_FACTORY_EXECUTOR";

const REVIEWABLE_REQUESTS_RESOURCE = "REVIEWABLE_REQUESTS_RESOURCE";
const TOKEN_REGISTRY_RESOURCE = "TOKEN_REGISTRY_RESOURCE";
const TOKEN_FACTORY_RESOURCE = "TOKEN_FACTORY_RESOURCE";

const CREATE_PERMISSION = "CREATE";
const EXECUTE_PERMISSION = "EXECUTE";

const TOKEN_REGISTRY_DEP = "TOKEN_REGISTRY";
const TOKEN_FACTORY_DEP = "TOKEN_FACTORY";

module.exports = {
  REVIEWABLE_REQUESTS_CREATOR,
  TOKEN_FACTORY_EXECUTOR,
  REVIEWABLE_REQUESTS_RESOURCE,
  TOKEN_REGISTRY_RESOURCE,
  TOKEN_FACTORY_RESOURCE,
  CREATE_PERMISSION,
  EXECUTE_PERMISSION,
  TOKEN_REGISTRY_DEP,
  TOKEN_FACTORY_DEP,
};
