const CREATE_PERMISSION = "CREATE";
const EXECUTE_PERMISSION = "EXECUTE";
const MINT_PERMISSION = "MINT";
const BURN_PERMISSION = "BURN";
const SPEND_PERMISSION = "SPEND";
const RECEIVE_PERMISSION = "RECEIVE";
const CHANGE_METADATA_PERMISSION = "CHANGE_METADATA";

const REVIEWABLE_REQUESTS_RESOURCE = "REVIEWABLE_REQUESTS_RESOURCE";
const TOKEN_REGISTRY_RESOURCE = "TOKEN_REGISTRY_RESOURCE";
const TOKEN_FACTORY_RESOURCE = "TOKEN_FACTORY_RESOURCE";

const TOKEN_REGISTRY_DEP = "TOKEN_REGISTRY";
const TOKEN_FACTORY_DEP = "TOKEN_FACTORY";

const DefaultTokenParams = {
  name: "name",
  symbol: "symbol",
  metadataURI: "URI",
  decimals: 18,
  totalSupplyCap: 0,
};

module.exports = {
  CREATE_PERMISSION,
  EXECUTE_PERMISSION,
  MINT_PERMISSION,
  BURN_PERMISSION,
  SPEND_PERMISSION,
  RECEIVE_PERMISSION,
  CHANGE_METADATA_PERMISSION,
  REVIEWABLE_REQUESTS_RESOURCE,
  TOKEN_REGISTRY_RESOURCE,
  TOKEN_FACTORY_RESOURCE,
  TOKEN_REGISTRY_DEP,
  TOKEN_FACTORY_DEP,
  DefaultTokenParams,
};
